1)numpy array operations 2)pandas Data manipulation and analysis 3)matplotlib and Seaborn Graphical Analysis 4)sklearn machine learning algorithms and techniques 5)statsmodels statistical analysis 6)scipy statistical analysis

In [3]:
import numpy as np

In [4]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [5]:
d=np.array(j)
d

array([5, 7, 2, 8, 4, 7])

In [6]:
d

array([5, 7, 2, 8, 4, 7])

In [7]:
type(d)

numpy.ndarray

In [8]:
d.shape

(6,)

In [12]:
d.size

6

In [13]:
k=([4,8,90.12],
   [56,78,54,20],
   [67,89,50,49],
   [77,88,22,55],
   [90,40,70,60])

In [14]:
m=[3,4,5,6,7,8,9,10,11,12]
m

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [15]:
list(range(3,13))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [16]:
list(range(3,13,3))

[3, 6, 9, 12]

In [17]:
list(range(5,500))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 1

In [18]:
tuple(range(5,506,100))

(5, 105, 205, 305, 405, 505)

In [19]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [20]:
range(-1,-10)

range(-1, -10)

In [21]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [22]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [1]:
[2.5,3,3.5,4,4.5]

[2.5, 3, 3.5, 4, 4.5]

In [5]:
for i in range(5,50,5):
    print("Data" ,i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [6]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j


[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [7]:
range(len(j))

range(0, 11)

In [8]:
range(8)

range(0, 8)

In [9]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])

In [10]:
x,y 

([5, 23, 62, 80, 77, 80], [87, 46, 84, 45, 33])

In [11]:
for i in range(len(j)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [12]:
import numpy as np

In [13]:
d=np.array([10,40,50,30,70])
d

array([10, 40, 50, 30, 70])

In [14]:
np.mean(d)

40.0

In [15]:
np.median(d)

40.0

In [16]:
np.var(d)


400.0

In [17]:
np.std(d)

20.0

In [18]:
np.max(d)

70

In [19]:
np.min(d)

10

In [20]:
np.quantile(d,0.25)

30.0

Q1=np.quantile(d,0.25)
Q2=np.quantile(d,0.5) Q3=np.quantile(d,0.75)

In [21]:
r=np.random.rand(5,3)  # range is from 0 to 1 standard normmaly DATA
r

array([[0.59170778, 0.11510195, 0.35170603],
       [0.17443905, 0.20892999, 0.87135854],
       [0.80643441, 0.32387788, 0.36500962],
       [0.01086006, 0.82562974, 0.70470067],
       [0.23827003, 0.147649  , 0.60327124]])

In [23]:
r.size

15

In [24]:
r.ndim

2

In [25]:
r.shape

(5, 3)

In [26]:
r=np.random.rand(5,3,2)
r

array([[[0.51156156, 0.94960787],
        [0.91098681, 0.12225407],
        [0.53776499, 0.62783417]],

       [[0.34840344, 0.19855423],
        [0.23556022, 0.22874139],
        [0.52621404, 0.81584582]],

       [[0.9773982 , 0.94814499],
        [0.45834558, 0.69329489],
        [0.36305149, 0.05572022]],

       [[0.24454114, 0.21767618],
        [0.7970295 , 0.15428835],
        [0.58156885, 0.05099433]],

       [[0.99029213, 0.22587118],
        [0.54981519, 0.65056899],
        [0.6923822 , 0.94695   ]]])

In [27]:
r=np.random.randn(30,1)   #-3 to +3 standard normally DATA
r

array([[-0.85669498],
       [ 0.35933395],
       [ 0.06448324],
       [-0.20695983],
       [ 0.24769925],
       [ 1.10013314],
       [ 1.14874691],
       [-1.44994678],
       [ 0.12395894],
       [-0.30709854],
       [ 0.79397873],
       [ 2.05700337],
       [-0.31800988],
       [ 0.69269207],
       [-0.72247231],
       [-0.30951249],
       [-0.48919139],
       [-1.34840374],
       [ 0.69073523],
       [ 0.35950479],
       [-0.47094085],
       [ 0.72508475],
       [ 0.64378486],
       [ 0.66609919],
       [-0.57835409],
       [-1.2111833 ],
       [ 0.40612633],
       [-0.49390176],
       [ 2.09849917],
       [ 0.2961206 ]])

In [28]:
np.random.normal(40,5)

32.947989837807434

In [29]:
np.random.normal(40,5,(5,4))  # (5,4) it is a shape and 40,5-40|5=20

array([[40.80398221, 42.59791201, 43.11583387, 31.9549697 ],
       [39.47633069, 40.62406455, 32.45510422, 40.00866131],
       [32.13331578, 42.98238806, 34.13577777, 30.95816708],
       [29.23628528, 41.91087175, 37.56660289, 48.58761661],
       [43.83167116, 35.41905169, 41.30707681, 44.06321017]])

In [30]:
np.random.normal(40,5,(5,4))  # (5,4) it is a shape and 40,5-40|5=20

array([[40.97736287, 43.58551487, 37.84925762, 45.94549726],
       [37.23472602, 37.58731713, 46.3034951 , 45.06705598],
       [31.11298842, 40.30849719, 38.86336109, 28.57796823],
       [41.88271281, 49.14314178, 34.78236828, 47.57149599],
       [31.56244533, 43.25994761, 42.24073532, 42.37032759]])

In [31]:
np.random.randint(35,91)

54