In [1]:
import numpy as np 

In [2]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [3]:
d=[]
for i in h:
    d.append(i+5)

In [4]:
d

[35, 25, 10, 13, 14]

In [5]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [6]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
k

[36, 4, 9, 81, 49, 25, 64]

In [7]:
s

(36, 4, 9, 81, 49, 25, 64)

In [8]:
m=[]
for i in s:
    if i>30:
        m.append(i)

In [9]:
m

[36, 81, 49, 64]

In [10]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])

In [11]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [12]:
arr*5

array([100, 250, 150, 350, 400, 200, 180, 270, 115, 490])

In [13]:
arr/2

array([10. , 25. , 15. , 35. , 40. , 20. , 18. , 27. , 11.5, 49. ])

In [ ]:
arr**2
